# Generated by Django 6.0.3 on 2026-04-26 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conference', '0001_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('recused', 'Recused')], default='pending', max_length=20)),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
                ('additional_comments', models.TextField(blank=True)),
                ('recommendation', models.CharField(blank=True, choices=[('strong_accept', 'Strong Accept'), ('accept', 'Accept'), ('weak_accept', 'Weak Accept'), ('borderline', 'Borderline'), ('weak_reject', 'Weak Reject'), ('reject', 'Reject')], max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_assigned', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='submissions.submission')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('submission', 'reviewer')},
            },
        ),
        migrations.CreateModel(
            name='ReviewCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, help_text='Short hint shown under the slider.', max_length=300)),
                ('weight', models.PositiveIntegerField(default=1, help_text='Used when calculating overall scores. 1 = equal weight.')),
                ('min_score', models.PositiveIntegerField(default=1)),
                ('max_score', models.PositiveIntegerField(default=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_criteria', to='conference.conference')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('conference', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ConflictOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Brief reason — e.g. co-author, colleague, competitor.')),
                ('declared_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_declared', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='submissions.submission')),
            ],
            options={
                'unique_together': {('submission', 'reviewer')},
            },
        ),
        migrations.CreateModel(
            name='ReviewScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.reviewcriterion')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='reviews.review')),
            ],
            options={
                'unique_together': {('review', 'criterion')},
            },
        ),
    ]
